import Head from 'next/head';
import HomeCard from '../components/HomeCard';
import FilterCard from '../components/FilterCard';
import Role from '../models/Role';

import { connectToDatabase } from '../util/mongodb';

export default function Home({ properties }) {
  return (
    <div>
      <Head>
        <title>HFLA Roles Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
      <div className="flex flex-col items-center justify-between mt-8 lg:items-start lg:flex-row lg:w-5/6 xl:w-1150">
        <div className="w-64 mb-8 top-8 lg:sticky">
          <FilterCard />
        </div>
        <div>
          {properties &&
            properties.map((property) => (
              <div className="mb-8 xl:mr-32">
                <HomeCard
                  id={property._id}
                  roleName={property.role_name}
                  projectName={property.project_name}
                  datePosted={property.createdAt}
                  description={property.description}
                  meetingTimes={property.meeting_times}
                  directions={property.directions}
                  timeCommitment={property.time_commitment}
                  about={property.about}
                  responsibilities={property.responsibilities}
                />
              </div>
            ))}
        </div>
      </div>
      </div>
      
    </div>
  );
}

export async function getServerSideProps(context) {
  await connectToDatabase();

  const data = await Role.find({});

  const properties = await JSON.parse(JSON.stringify(data));

  return {
    props: { properties: properties },
  };
}
