import Head from 'next/head';
import Image from 'next/image';
import projectImage from '../../../public/images/civic-tech-index.png';
import RolesCard from '../../components/RolesCard';

import { connectToDatabase } from '../../util/mongodb';

let ObjectId = require('mongodb').ObjectId;

export default function role({ properties }) {
  return (
    <div>
      <Head>
        <title>HFLA Roles Prototype</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* container for top section */}
      <div className="flex flex-row w-full p-8 justify-between bg-white">
        {/* container for left top section */}
        <div>
          <div>
            <Image src={projectImage} alt="Civic Tech Index Project Image" width={150} height={100} />
          </div>
          <div>
            <h3 className="font-bold my-4">Team Meeting Times</h3>
            <p>{properties.meeting_times}</p>
          </div>
        </div>
        {/* vertical line */}
        <div className="border-l-2 border-gray-200 h-64"></div>
        {/* container for right top section */}
        <div className="mt-4">
          <p className="text-gray-500 text-sm">Posted: {properties.date_posted}</p>
          <h1 className="font-bold text-2xl mt-4 mb-8">{properties.role_name}</h1>
          <p>
            <strong>Project: </strong>
            {properties.project_name}
          </p>
          <p>
            <strong>Time commitment: </strong>
            {properties.time_commitment}
          </p>
          <p>
            <strong>Positions: </strong>Need 2-3 volunteers
          </p>
        </div>
      </div>
      {/* container for page card */}
      <div>
        <RolesCard
          id={properties._id}
          roleName={properties.role_name}
          projectName={properties.project_name}
          datePosted={properties.date_posted}
          description={properties.description}
          meetingTimes={properties.meeting_times}
          directions={properties.directions}
          timeCommitment={properties.time_commitment}
          about={properties.about}
          responsibilities={properties.responsibilities}
        />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { db } = await connectToDatabase();

  const data = await db.collection('roles').findOne({ _id: ObjectId(`${context.params.id}`) });

  const properties = await JSON.parse(JSON.stringify(data));

  return {
    props: { properties: properties },
  };
}
